---
abstract: 'Update make files.'
author:
  - 'Vadim Zeitlin <vz-cpan@zeitlins.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Makefile-Update
recommends:
  Text::Diff: '0'
version: '0.2'
